apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/reactive-tech/kubegres/v1.16/kubegres.yaml

images:
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: zjuici/mirror.kubebuilder.kube-rbac-proxy
