apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
spec:
   replicas: 1
   image: postgres:15.2
   database:
      size: 10Gi
   customConfig: postgres-init-conf
   # Kubegres does not support envFrom, so we have to list them one by one.
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres
              key: SUPER_USER_PASSWORD
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres
              key: REPLICATION_USER_PASSWORD
      - name: DEX_USERNAME
        valueFrom:
            secretKeyRef:
               name: postgres
               key: DEX_USERNAME
      - name: DEX_PASSWORD
        valueFrom:
            secretKeyRef:
               name: postgres
               key: DEX_PASSWORD
      - name: DEX_DATABASE
        valueFrom:
            secretKeyRef:
               name: postgres
               key: DEX_DATABASE
