apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubegres.yaml

configMapGenerator:
  - name: postgres-init-conf
    files:
      - primary_init_script.sh

secretGenerator:
  - name: postgres
    envs:
      - secret-params.env

generatorOptions:
  disableNameSuffixHash: true
