apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

labels:
  - pairs:
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/version: v7.6.0
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false

resources:
  # TODO: labels will get overriden if we kustomize third-party manifests here
  # - ../third-party/redis
  - rbac.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: oauth2-proxy
    files:
      - oauth2-proxy.yaml
    # we will mount configmaps so we can't use suffix hash
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: oauth2-proxy
    envs:
      - secret-params.env

images:
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newName: zjuici/mirror.oauth2-proxy.oauth2-proxy
    newTag: v7.6.0
