apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/manifests//apps/jupyter/jupyter-web-app/upstream/overlays/istio/?ref=v1.9.0

configMapGenerator:
  - name: config
    behavior: merge
    files:
      - spawner_ui_config.yaml
