apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - third-party/kubegres/base
  - https://github.com/kubeflow/manifests//common/dex/overlays/istio/?ref=v1.6.1

configMapGenerator:
  - name: dex
    behavior: merge
    files:
      - config.yaml

images:
  - name: ghcr.io/dexidp/dex
    newName: docker.io/dexidp/dex
    newTag: v2.36.0-distroless
