apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - third-party/kubegres/base
  - https://github.com/kubeflow/manifests//common/dex/overlays/oauth2-proxy/?ref=v1.8.1

configMapGenerator:
  - name: dex
    behavior: merge
    files:
      - config.yaml

# IDK why specifying target not working, I have to specify the namespace in the patch file
patches:
  - path: patches/virtualservice.yaml

images:
  - name: ghcr.io/dexidp/dex
    newName: docker.io/dexidp/dex
    newTag: v2.39.1-distroless
